

//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: rapid.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate MembershipServiceClient, then call methods of this protocol to make API calls.
public protocol MembershipServiceClientProtocol {
  func sendRequest(_ request: RapidRequest, callOptions: CallOptions?) -> UnaryCall<RapidRequest, RapidResponse>
}

public final class MembershipServiceClient: GRPCClient, MembershipServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the MembershipService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to sendRequest
  ///
  /// - Parameters:
  ///   - request: Request to send to sendRequest.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func sendRequest(_ request: RapidRequest, callOptions: CallOptions? = nil) -> UnaryCall<RapidRequest, RapidResponse> {
    return self.makeUnaryCall(path: "/MembershipService/sendRequest",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol MembershipServiceProvider: CallHandlerProvider {
  func sendRequest(request: RapidRequest, context: StatusOnlyCallContext) -> EventLoopFuture<RapidResponse>
}

extension MembershipServiceProvider {
  public var serviceName: String { return "MembershipService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "sendRequest":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.sendRequest(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload`
extension Endpoint: GRPCProtobufPayload {}
extension RapidRequest: GRPCProtobufPayload {}
extension RapidResponse: GRPCProtobufPayload {}
extension NodeId: GRPCProtobufPayload {}
extension JoinMessage: GRPCProtobufPayload {}
extension JoinResponse: GRPCProtobufPayload {}
extension BatchedAlertMessage: GRPCProtobufPayload {}
extension AlertMessage: GRPCProtobufPayload {}
extension Response: GRPCProtobufPayload {}
extension FastRoundPhase2bMessage: GRPCProtobufPayload {}
extension Rank: GRPCProtobufPayload {}
extension Phase1aMessage: GRPCProtobufPayload {}
extension Phase1bMessage: GRPCProtobufPayload {}
extension Phase2aMessage: GRPCProtobufPayload {}
extension Phase2bMessage: GRPCProtobufPayload {}
extension ConsensusResponse: GRPCProtobufPayload {}
extension Metadata: GRPCProtobufPayload {}
extension LeaveMessage: GRPCProtobufPayload {}
extension ProbeMessage: GRPCProtobufPayload {}
extension ProbeResponse: GRPCProtobufPayload {}
